### PR TITLE
Added a new effect to change the color of picker's title

### PR DESCRIPTION
**Pull request by acaliaro**
It's only for android... I don't know if I should change the name because Picker have other "Colors" that can be changed....

### CODE REVIEW

**Comment by acaliaro** [comment]
Hi guys. I have the effect also for UWP picker. Let me know how to do the PR...

**Comment by Depechie** [comment]
Next week I'll go over this - first I need to go through the Naming guidelines from James and will report back

**Comment by acaliaro** [comment]
Where are these guidelines? Will be public?

**Comment by Depechie** [comment]
When we have a consensus, we'll post them :)

**Comment by acaliaro** [comment]
what should I do to solve this conflict??

**Comment by Depechie** [comment]
@acaliaro no worries, I'll tackle this! Tried yesterday but ran out of time, will do a new effort this week :)

**Comment by JanJoris** [comment]
I have a proposal @acaliaro. First, move your changes to a new branch.

`git branch cherry`

Next, reset the master branch to wher it was and pull the latest changes

`git reset head~4; git pull`

This way you are back to where you started. Let's create a new branch to actually work on.

`git checkout -b feature/color-picker`

And cherry pick all the commits you made (and resolve the conflicts).
You can find them by using `git log cherry`.

In an ideal world we could just rebase, but that creates quite the mess, just as a merge.
I have no idea what happened in this repo to cause this (neither do I feel like investigating that), but this will make sure the changes actually reflect what happened.

**Comment by Depechie** [comment]
We cloned this PR into a new branch and merged DEV locally to fix merge conflicts and pushed it as new PR : https://github.com/FormsCommunityToolkit/Effects/pull/44

So that PR should fix everything and add these changes :)

**Pull request closed without merging**
