### PR TITLE
Finalize CI Build + Reorganization + Renaming

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Re-organized files to match Converters
Added CI for Appveryor and now building
Updated code based off discussion

### CODE REVIEW

**Comment by Depechie** [comment]
Let us get this in and do seperate PR's later to tidy up!

**Comment by jamesmontemagno** [comment]
Done! Boom

**Comment by jimbobbennett** [comment]
👍

**Comment by sam-ss** [comment]
:+1: :+1:

**Pull request merged**
